"""Thresholds for filter evidence — mostly FPVPIDlab ``constants.ts`` (WU13)."""

from __future__ import annotations

# Segment selection (FPVPIDlab)
THROTTLE_MIN_FLIGHT = 0.15
THROTTLE_MAX_HOVER = 0.75
GYRO_STEADY_MAX_STD = 50.0
YAW_STEADY_MULTIPLIER = 1.5
SEGMENT_MIN_DURATION_S = 0.5
SEGMENT_WINDOW_DURATION_S = 0.15
SWEEP_MIN_THROTTLE_RANGE = 0.4
SWEEP_MIN_DURATION_S = 2.0
SWEEP_MAX_DURATION_S = 15.0
SWEEP_MAX_RESIDUAL = 0.15
MAX_SEGMENTS = 5

# Noise (FPVPIDlab)
PEAK_PROMINENCE_DB = 6.0
PEAK_MIN_SPACING_HZ = 15.0
PEAK_LOCAL_WINDOW_BINS = 50
NOISE_FLOOR_PERCENTILE = 0.25
NOISE_LEVEL_HIGH_DB = -20.0
NOISE_LEVEL_MEDIUM_DB = -40.0
FRAME_RESONANCE_MIN_HZ = 80.0
FRAME_RESONANCE_MAX_HZ = 200.0
ELECTRICAL_NOISE_MIN_HZ = 500.0
FREQUENCY_MIN_HZ = 20.0
FREQUENCY_MAX_HZ = 1000.0
FFT_WINDOW_SIZE = 4096
FFT_OVERLAP = 0.5
DB_SENTINEL = -240.0
POWER_FLOOR = 1e-24

# Group delay (FPVPIDlab GroupDelayEstimator)
GROUP_DELAY_REFERENCE_HZ = 80.0
GROUP_DELAY_WARNING_MS = 2.0
FILTER_LATENCY_BUDGET_DEFAULT_GYRO_MS = 2.0
FILTER_LATENCY_BUDGET_DEFAULT_DTERM_MS = 3.5

# Dynamic lowpass evidence (FPVPIDlab DynamicLowpassRecommender)
DYNAMIC_LOWPASS_NOISE_INCREASE_DB = 6.0
DYNAMIC_LOWPASS_MIN_BANDS = 3
DYNAMIC_LOWPASS_MIN_CORRELATION = 0.6
DYNAMIC_LOWPASS_RATIO = 2.0

# Non-actionable candidate heuristic (FPVPIDlab FilterRecommender computeNoiseBasedTarget)
NOISE_FLOOR_VERY_NOISY_DB = 0.0
NOISE_FLOOR_VERY_CLEAN_DB = -60.0
GYRO_LPF1_MIN_HZ = 75
GYRO_LPF1_MAX_HZ = 300
DTERM_LPF1_MIN_HZ = 70
DTERM_LPF1_MAX_HZ = 200
PROPWASH_GYRO_LPF1_FLOOR_HZ = 100
PROPWASH_FLOOR_BYPASS_DB = -5.0
NOISE_TARGET_DEADZONE_HZ = 5

PROVENANCE = {
    "upstream": "https://github.com/eddycek/fpvpidlab",
    "commit": "76354a022b331a9b466727f9a67ba369a12067ac",
    "license": "GPL-3.0-only",
    "capability": "filter_evidence",
    "actionable": False,
}
